### ISSUE TITLE
Wrong import in get_bbs_data

### ISSUE THREAD

**Issue by richardjtelford** [TrashBirdEcology/bbsAssistant#105]
https://github.com/trashbirdecology/bbsAssistant/blob/a1a4e5569d1e205cf4ca3e25df71a82554963d68/R/get_bbs_data.R#L13

This should be

` #' @importFrom dplyr filter`

I can send a pull request if you would like me to

**Comment by trashbirdecology** [comment]
Thanks. This has been addressed in the new major update branch, soon to be pushed into main .

https://github.com/trashbirdecology/bbsAssistant/tree/major-update-50stop
