### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by GabsPalomo** [TrashBirdEcology/bbsAssistant#30]
Not sure if this should be an issue, but I was wondering what type of information you want to include in the summary. 

I understand that the package is basically downloading the data that already exists in this website to make it more user friendly and more importantly R-friendly. However, would you like to include the following in this summary?

1. Brief overview of the breeding birds survey methods? (cited obviously)
2. Information on the BBS website/data?
3. Why we are doing this package? User friendly, R-interface, etc.??

These are the only things I can think of at the moment to include in the summary. If you agree with them I can write them up for your review.

**Comment by trashbirdecology** [comment]
> Brief overview of the breeding birds survey methods? (cited obviously)
- I think that's a good idea,  maybe just a sentence or two.  We should certainly point to the web addresses

> Information on the BBS website/data?
- Yes yes yes
- We should probably also describe (and point to and cite) the BBS analysis and results (webpage, and Sauer et al.). 
- Also important I think are the screenshots that are included in the README (and are also in the [images folder](/images/).

> Why we are doing this package? User friendly, R-interface, etc.??
- Mostly to facilitate the ease with which BBS data are accessed and imported into R
- Big points:  **we are saving a lot of people a lot of time**. (1) download the bbs data (as .zip into a temp folder; avoiding the point and click style of downloading the data); (1a) subset these data to remove any unwanted species, locations, etc.; (1b) compress into feather files and save to disk for local storage; (1c) import many .feather BBS state files; (1d) ; (2) web scraping which uniquely allows for retrieval of the credibility measures + the pop trend results

I think we should also include a sentence about the target audience (users of the BBS data... lol).

@GabsPalomo  please @  me if you have more questions!
