### ISSUE TITLE
README.rmd

### ISSUE THREAD

**Issue by trashbirdecology** [TrashBirdEcology/bbsAssistant#4]
Create README.md from README.rmd after getting bulk of functions imported and cleaned. 

Add a quick runthrough of primary features to the readme.rmd

**Comment by GabsPalomo** [comment]
Jes I can go through the README.md to see if the examples are easily understood or if more comments or other lines of code could be added to make it more understandable. Is this ok?

**Comment by trashbirdecology** [comment]
Most definitely!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
