### ISSUE TITLE
Confusing API for `subset_speciesList`

### ISSUE THREAD

**Issue by ethanwhite** [TrashBirdEcology/bbsAssistant#66]
This is recommendation based on my experience while reviewing this package for JOSS (https://github.com/openjournals/joss-reviews/issues/1768).

**Is your feature request related to a problem? Please describe.**

I was confused by the API for `subset_speciesList`. My reading of the vignette was that passing `aou.ind` would subset the data to only the provided AOU. This matched my intuition for how a function named `subset_speciesList` would work. However, as documented in the function documentation the behavior is actually the opposite, with the list of species provided being removed and all other species kept. 

**Describe the solution you'd like**

I would consider either renaming this function to something like `remove_species` or changing the argument names to something like `drop_species`. This would make the i

**Describe alternatives you've considered**

Clarifying the vignette to make the behavior clearer would be another option, but I think intuitive naming would go a long way to preventing user confusion.

**Comment by trashbirdecology** [comment]
Agreed. Will update to include remove_spp.. Not sure what I was thinking..

**Comment by trashbirdecology** [comment]
@ethanwhite I have simplified subsetting by removing functions eluding to this, and rather supply  examples of species-level (and other taxonomic level) subsetting in the vignette [currently housed in here](https://github.com/TrashBirdEcology/bbsAssistant/blob/master/vignettes/quick-overview.Rmd). 



Future development includes more niche species subsetting (e.g., function or argument to remove species with crappy detectability).
