### ISSUE TITLE
Minor release update: update links to reflect new release in ScienceBase

### ISSUE THREAD

**Issue by trashbirdecology** [TrashBirdEcology/bbsAssistant#96]
Need to update the links to the new [ScienceBase records](https://www.sciencebase.gov/catalog/item/5ea04e9a82cefae35a129d65).

**Comment by AdamCSmithCWS** [comment]
I gather you're working on this, but just in case, the ftp site seems to have been removed. The ScienceBase version seems to be the only access-point now.
E.g., I'm getting this error when trying to download:

bbs<- bbsAssistant::quick_get_bbs(state.names = c("Florida", "Nebraska"),  overwrite.bbs = FALSE, overwrite.routes = FALSE,  get.conditions = TRUE, overwrite.conditions = FALSE) # get weather conditions, does not overwrite

trying URL 'ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/States/Florida.zip'
Error in download.file(url = urls[i], destfile = fn.local) : 
  cannot open URL 'ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/States/Florida.zip'
In addition: Warning message:
In download.file(url = urls[i], destfile = fn.local) :
  InternetOpenUrl failed: ''

**Comment by trashbirdecology** [comment]
Thanks, Adam, I was not aware of the move to ScienceBase earlier.

**Comment by trashbirdecology** [comment]
Resolved.
